@extends('themes.ino.app_ino')

@section('title', 'Privacy Policy')

@section('content')
<div class="col-inner text-center container" style="background-color:#fff;margin-top: 133px;margin-bottom: 40px;">
<h1 class="uppercase" style="text-align: center;">Privacy Policy</h1>
<p style="text-align: left;"><span style="font-weight: 400;">This privacy notice discloses the privacy practices for&nbsp;</span><b>BidHub </b><span style="font-weight: 400;">and our website; <a class="vglnk" href="http://www.bidhub.com" rel="nofollow"><span>www</span><span>.</span><span>bidhub</span><span>.</span><span>com</span></a></span><b>.</b><span style="font-weight: 400;">&nbsp;This privacy notice applies solely to information collected by this website, except where stated otherwise. It will notify you of the following:</span></p>
<ul style="text-align: left;">
<li style="font-weight: 400;"><span style="font-weight: 400;">What information we collect;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">With whom it is shared;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">How it can be corrected;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">How it is secured;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">How policy changes will be communicated; and</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">How to address concerns over misuse of personal data.</span></li>
</ul>
<p style="text-align: center;"><span style="font-weight: 400;">&nbsp;</span><b>Information Collection, Use, and Sharing</b><span style="font-weight: 400;">&nbsp;</span><span style="font-weight: 400;"><br></span><span style="font-weight: 400;"><br></span><span style="font-weight: 400;">We are the sole owners of the information collected on this site. We only have access to/collect information that you voluntarily give us via email or other direct contact from you. </span></p>
<p style="text-align: left;"><span style="font-weight: 400;">We will not sell or rent this information to anyone.&nbsp;</span></p>
<p style="text-align: left;"><span style="font-weight: 400;">We will use your information to respond to you, regarding the reason you contacted us. We will not share your information with any third party outside of our organization, other than as necessary to fulfill your request, e.g., to ship an order.</span></p>
<p style="text-align: left;"><span style="font-weight: 400;">Unless you ask us not to, we may contact you via email in the future to tell you about specials, new products or services, or changes to this privacy policy.&nbsp;</span></p>
<p><b></b></p><center><b>Your Access to and Control Over Information</b></center><p></p>
<p style="text-align: left;"><span style="font-weight: 400;">&nbsp;</span><span style="font-weight: 400;"><br></span><span style="font-weight: 400;"><br></span><span style="font-weight: 400;">You may opt out of any future contacts from us at any time. You can do the following at any time by contacting us via the email address or phone number provided on our website:</span></p>
<ul style="text-align: left;">
<li style="font-weight: 400;"><span style="font-weight: 400;">See what data we have about you, if any.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Change/correct any data we have about you.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Have us delete any data we have about you.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Express any concern you have about our use of your data</span></li>
</ul>
<p style="text-align: left;"><b></b></p><center><b>Registration</b></center><p></p>
<p style="text-align: left;"><span style="font-weight: 400;">&nbsp;</span><span style="font-weight: 400;"><br></span><span style="font-weight: 400;"><br></span><span style="font-weight: 400;">In order to use this website, a user must first complete the registration form. During registration a user is required to give certain information (such as name and email address). This information is used to contact you about the products/services on our site in which you have expressed interest. At your option, you may also provide demographic information (such as gender or age) about yourself, but it is not required.</span></p>
<p><b></b></p><center><b>Orders</b></center><p></p>
<p style="text-align: left;"><span style="font-weight: 400;">&nbsp;</span><span style="font-weight: 400;"><br></span><span style="font-weight: 400;"><br></span><span style="font-weight: 400;">We request information from you on our order form. To buy from us, you must provide contact information (like name and shipping address) and financial information (like credit card number, expiration date). This information is used for billing purposes and to fill your orders. If we have trouble processing an order, we’ll use this information to contact you.</span></p>
<p><b></b></p><center><b>Sharing</b></center><p></p>
<p style="text-align: left;"><span style="font-weight: 400;">&nbsp;</span><span style="font-weight: 400;"><br></span><span style="font-weight: 400;"><br></span><span style="font-weight: 400;">We share aggregated demographic information with our partners and advertisers. This is not linked to any personal information that can identify any individual person.</span></p>
<p style="text-align: left;"><i><span style="font-weight: 400;">And/or:</span></i><span style="font-weight: 400;">&nbsp;</span><span style="font-weight: 400;"><br></span><span style="font-weight: 400;"><br></span><span style="font-weight: 400;">We use an outside shipping company to ship orders, and a credit card processing company to bill users for goods and services. These companies do not retain, share, store or use personally identifiable information for any secondary purposes beyond filling your order.</span></p>
<p style="text-align: left;"><i><span style="font-weight: 400;">And/or:</span></i><span style="font-weight: 400;">&nbsp;</span><span style="font-weight: 400;"><br></span><span style="font-weight: 400;"><br></span><span style="font-weight: 400;">We partner with another party to provide specific services. When the user signs up for these services, we will share names, or other contact information that is necessary for the third party to provide these services. These parties are not allowed to use personally identifiable information except for the purpose of providing these services.</span></p>
<p><b></b></p><center><b>Security</b></center><p></p>
<p style="text-align: left;"><span style="font-weight: 400;">&nbsp;</span><span style="font-weight: 400;"><br></span><span style="font-weight: 400;"><br></span><span style="font-weight: 400;">We take precautions to protect your information. When you submit sensitive information via the website, your information is protected both online and offline.</span></p>
<p style="text-align: left;"><span style="font-weight: 400;">Wherever we collect sensitive information (such as credit card data), that information is encrypted and transmitted to us in a secure way. You can verify this by looking for a closed lock icon at the bottom of your web browser, or looking for “https” at the beginning of the address of the web page.</span></p>
<p style="text-align: left;"><span style="font-weight: 400;">While we use encryption to protect sensitive information transmitted online, we also protect your information offline. Only employees who need the information to perform a specific job (e.g. billing or customer service) are granted access to personally identifiable information. The computers/servers on which we store personally identifiable information are kept in a secure environment.</span></p>
<p><b></b></p><center><b>Cookies</b></center><p></p>
<p style="text-align: left;"><span style="font-weight: 400;">&nbsp;</span><span style="font-weight: 400;"><br></span><span style="font-weight: 400;"><br></span><span style="font-weight: 400;">We use “cookies” on this site. A cookie is a piece of data stored on a site visitor’s hard drive to help us improve your access to our site and identify repeat visitors to our site. For instance, when we use a cookie to identify you, you would not have to log in a password more than once, thereby saving time while on our site. Cookies can also enable us to track and target the interests of our users to enhance their experience on our site. Usage of a cookie is in no way linked to any personally identifiable information on our site.</span></p>
<p style="text-align: left;"><span style="font-weight: 400;">Some of our business partners may use cookies on our site (e.g., advertisers). However, we have no access to or control over these cookies.</span></p>
<p><b></b></p><center><b>Links</b></center><span style="font-weight: 400;"><p></p>
<p style="text-align: left;">&nbsp;<span style="font-weight: 400;"><br></span><span style="font-weight: 400;"><br></span><span style="font-weight: 400;">This web site contains links to other sites. Please be aware that we are not responsible for the content or privacy practices of such other sites. We encourage our users to be aware when they leave our site and to read the privacy statements of any other site that collects personally identifiable information.</span></p>
<p><b></b></p><center><b>Surveys &amp; Contests</b></center><span style="font-weight: 400;"><p></p>
<p style="text-align: left;">&nbsp;<span style="font-weight: 400;"><br></span><span style="font-weight: 400;"><br></span><span style="font-weight: 400;">From time-to-time our site requests information via surveys or contests. Participation in these surveys or contests is completely voluntary and you may choose whether or not to participate and therefore disclose this information. Information requested may include contact information (such as name and shipping address), and demographic information (such as zip code, age level). Contact information will be used to notify the winners and award prizes. Survey information will be used for purposes of monitoring or improving the use and satisfaction of this site.</span></p>
<p style="text-align: left;">
</p></span></span></div>
@endsection
